"""removed foregin key constraint from farm_h3_cells

Revision ID: 024286745a17
Revises: 4fed38d757d9
Create Date: 2026-05-28 13:31:36.865478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '024286745a17'
down_revision: Union[str, Sequence[str], None] = '4fed38d757d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('farm_h3_cells_h3_index_fkey'), 'farm_h3_cells', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('farm_h3_cells_h3_index_fkey'), 'farm_h3_cells', 'h3_cells', ['h3_index'], ['h3_index'])
    # ### end Alembic commands ###
