"""make village nullable in farms

Revision ID: 44522c7a1c9a
Revises: 5b33b983b42e
Create Date: 2026-05-26 15:37:33.796632

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = "44522c7a1c9a"
down_revision: Union[str, Sequence[str], None] = "5b33b983b42e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("farms", "village_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
