"""add farm h3 cells

Revision ID: 4fed38d757d9
Revises: 8390eca0a0bb
Create Date: 2026-05-27 11:58:53.419475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fed38d757d9'
down_revision: Union[str, Sequence[str], None] = '8390eca0a0bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farm_h3_cells',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('h3_index', sa.String(), nullable=False),
    sa.Column('resolution', sa.Integer(), nullable=False),
    sa.Column('coverage_ratio', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['h3_index'], ['h3_cells.h3_index'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_farm_h3_farm_resolution', 'farm_h3_cells', ['farm_id', 'resolution'], unique=False)
    op.create_index('idx_farm_h3_h3_resolution', 'farm_h3_cells', ['h3_index', 'resolution'], unique=False)
    op.create_index(op.f('ix_farm_h3_cells_farm_id'), 'farm_h3_cells', ['farm_id'], unique=False)
    op.create_index(op.f('ix_farm_h3_cells_h3_index'), 'farm_h3_cells', ['h3_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_farm_h3_cells_h3_index'), table_name='farm_h3_cells')
    op.drop_index(op.f('ix_farm_h3_cells_farm_id'), table_name='farm_h3_cells')
    op.drop_index('idx_farm_h3_h3_resolution', table_name='farm_h3_cells')
    op.drop_index('idx_farm_h3_farm_resolution', table_name='farm_h3_cells')
    op.drop_table('farm_h3_cells')
    # ### end Alembic commands ###
