"""create farm registry tables

Revision ID: 80998caed841
Revises: 44522c7a1c9a
Create Date: 2026-05-26 16:09:56.090946

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = "80998caed841"
down_revision: Union[str, Sequence[str], None] = "44522c7a1c9a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "farm_boundaries",
        sa.Column(
            "boundary",
            geoalchemy2.types.Geometry(
                geometry_type="POLYGON",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
    )
    op.add_column(
        "farm_boundaries", sa.Column("boundary_hash", sa.String(), nullable=False)
    )
    op.add_column("farm_boundaries", sa.Column("version", sa.Integer(), nullable=False))
    op.add_column(
        "farm_boundaries", sa.Column("is_active", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "farm_boundaries",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.drop_index(
        op.f("idx_farm_boundaries_geometry"),
        table_name="farm_boundaries",
        postgresql_using="gist",
    )
    op.create_index(
        "idx_farm_boundaries_geometry",
        "farm_boundaries",
        ["boundary"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_unique_constraint(None, "farm_boundaries", ["boundary_hash"])
    op.drop_column("farm_boundaries", "geometry")
    op.add_column("farmers", sa.Column("aadhaar_reference", sa.String(), nullable=True))
    op.add_column("farmers", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.add_column(
        "farmers",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.alter_column(
        "farmers", "farmer_type", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_constraint(op.f("farmers_aadhaar_hash_key"), "farmers", type_="unique")
    op.drop_constraint(op.f("farmers_mobile_number_key"), "farmers", type_="unique")
    op.drop_column("farmers", "aadhaar_hash")
    op.add_column("farms", sa.Column("primary_crop", sa.String(), nullable=True))
    op.add_column("farms", sa.Column("irrigation_type", sa.String(), nullable=True))
    op.add_column("farms", sa.Column("soil_type", sa.String(), nullable=True))
    op.add_column("farms", sa.Column("ownership_type", sa.String(), nullable=False))
    op.add_column(
        "farms", sa.Column("registration_status", sa.String(), nullable=False)
    )
    op.add_column("farms", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.add_column(
        "farms",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.alter_column("farms", "village_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
