"""make village nullable in farms--2

Revision ID: aafe062757af
Revises: e7cd3b3f0a58
Create Date: 2026-05-26 20:00:17.875702

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = "aafe062757af"
down_revision: Union[str, Sequence[str], None] = "e7cd3b3f0a58"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("farms", "village_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
