"""make village nullable in farms

Revision ID: e7cd3b3f0a58
Revises: 80998caed841
Create Date: 2026-05-26 19:52:44.622710

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = "e7cd3b3f0a58"
down_revision: Union[str, Sequence[str], None] = "80998caed841"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
