"""fix farm hierarchy schema

Revision ID: ef2600931b69
Revises: aafe062757af
Create Date: 2026-05-26 22:24:34.391876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef2600931b69'
down_revision: Union[str, Sequence[str], None] = 'aafe062757af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('farm_boundaries_boundary_hash_key'), 'farm_boundaries', type_='unique')
    op.create_index(op.f('ix_farm_boundaries_boundary_hash'), 'farm_boundaries', ['boundary_hash'], unique=False)
    op.create_index(op.f('ix_farmers_mobile_number'), 'farmers', ['mobile_number'], unique=True)
    op.add_column('farms', sa.Column('block_id', sa.Integer(), nullable=False))
    op.add_column('farms', sa.Column('village_name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'farms', 'blocks', ['block_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'farms', type_='foreignkey')
    op.drop_column('farms', 'village_name')
    op.drop_column('farms', 'block_id')
    op.drop_index(op.f('ix_farmers_mobile_number'), table_name='farmers')
    op.drop_index(op.f('ix_farm_boundaries_boundary_hash'), table_name='farm_boundaries')
    op.create_unique_constraint(op.f('farm_boundaries_boundary_hash_key'), 'farm_boundaries', ['boundary_hash'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
